services:
    advoid:
        build: .
        container_name: advoid
        ports:
            - "853:853"
            - "8053:8053"
            - "53:53/udp"
            - "53:53/tcp"
        restart: always
        env_file:
            - .env
